---
home_dir: "/home/{{ filesystem.user }}"
projects_dir: "{{ home_dir }}/projects"
working_dir: "{{ home_dir }}/.hirsh"
user_service_dir: "{{ home_dir }}/.config/systemd/user"
project_dir: "{{ projects_dir }}/hirsh"
venv_dir: "{{ project_dir }}/.venv"

service_path: "{{ user_service_dir }}/hirsh.service"
config_path: "{{ working_dir }}/config.yaml"
pid_path: "{{ working_dir }}/hirsh.pid"
requirements_path: "{{ project_dir }}/requirements.txt"
python_path: "{{ venv_dir }}/bin/python"
hirsh_path: "{{ project_dir }}/hirsh"